# Configure dependabot automatic version upgrades
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
registries:
  github-flatmap:
    type: maven-repository
    url: https://maven.pkg.github.com/onthegomap
    # workaround for github maven packages not supporting anonymous access (https://github.community/t/download-from-github-package-registry-without-authentication/14407/111)
    username: 'flatmapbot'
    password: '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'
updates:
  - package-ecosystem: maven
    directory: "/"
    open-pull-requests-limit: 1
    schedule:
      interval: daily
      time: "04:30"
      timezone: America/New_York
    labels:
      - dependencies
    ignore:
      - dependency-name: "com.graphhopper:graphhopper-reader-osm"
  - package-ecosystem: maven
    directory: "/flatmap-examples"
    open-pull-requests-limit: 1
    schedule:
      interval: daily
      time: "04:30"
      timezone: America/New_York
    labels:
      - dependencies
    ignore:
      - dependency-name: "com.onthegomap.flatmap:*"
    registries:
      - github-flatmap
  - package-ecosystem: github-actions
    directory: "/"
    open-pull-requests-limit: 1
    schedule:
      interval: daily
      time: "04:30"
      timezone: America/New_York
    labels:
      - dependencies
